import { SOURCES } from '@/data/sources'
export default function About() {
  return <article className="page-width about-page"><p className="eyebrow">SOBRE O PULSO</p><h1>Informação clara.<br/>Cuidado com responsabilidade.</h1><p>O Pulso reúne orientações educativas para os primeiros minutos de uma emergência no Brasil. A prioridade é proteger quem ajuda e acionar o atendimento profissional: SAMU 192 e Bombeiros 193.</p>
    <h2>De onde vêm as orientações</h2><p>Conteúdo revisado em setembro de 2026 com base nas diretrizes de ressuscitação de 2025, nas diretrizes de primeiros socorros de 2024 e nas informações oficiais brasileiras abaixo. O ano da revisão não significa que exista uma nova diretriz publicada em 2026.</p><ol className="source-list">{Object.values(SOURCES).map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></li>)}</ol>
    <h2>O que o site pode — e não pode — fazer</h2><p>Os guias não avaliam uma pessoa, não fazem diagnóstico e não substituem treinamento prático, a regulação do SAMU ou a equipe de resgate. As perguntas ajudam a localizar informação; não excluem uma emergência. A revisão de referências não equivale a uma validação clínica por profissional responsável.</p><p>As técnicas de adultos não devem ser aplicadas indiscriminadamente a bebês ou crianças. O guia infantil diferencia as faixas etárias e não cobre reanimação durante o parto. A área de animais orienta apenas proteção e encaminhamento veterinário.</p>
    <h2 id="voz">Como usar a voz</h2><p>Na busca, toque no microfone e fale o nome de uma situação. Nos guias, use Ouvir para escutar a etapa completa, incluindo alertas. Você pode ajustar o ritmo ou ativar a leitura dos próximos passos. Toque em Falar comando e diga “próximo passo”, “repetir”, “voltar”, “não consegui”, “ajuda” ou “opção 1”. Cada toque ouve uma fala; a escuta encerra ao receber o comando.</p><p>Nas perguntas, “próximo” não pula a decisão. Uma opção reconhecida por voz precisa ser confirmada na tela. O comando “ajuda” mostra os telefones; a ligação depende de uma ação sua. Durante a leitura, o microfone é interrompido para não confundir a própria voz do site com a sua.</p><p>A disponibilidade e a naturalidade da voz dependem do navegador e das vozes instaladas no aparelho. O microfone requer permissão e conexão segura (HTTPS). Se não funcionar, todos os guias continuam acessíveis por toque e teclado.</p>
    <h2>Privacidade e conexão</h2><p>Não há cadastro, histórico de casos ou gravação de áudio no código do Pulso. O tamanho de texto fica salvo no navegador; a leitura automática vale para a sessão atual. Ao ativar a voz, o navegador pode enviar áudio ou texto ao serviço de reconhecimento ou síntese do próprio fornecedor. Evite falar nomes, documentos ou dados pessoais.</p><p>Esta versão precisa de conexão para abrir e recarregar o site. Não promete funcionamento offline. A voz pode precisar de internet mesmo depois de a página estar aberta. Em uma emergência, não dependa exclusivamente do aplicativo.</p>
    <h2>Acessibilidade</h2><p>Use o controle de texto no cabeçalho, navegue com Tab e ative os botões com Enter ou Espaço. A interface respeita a preferência de movimento reduzido do aparelho. A informação falada também está disponível em texto.</p>
  </article>
}
